title: <p align="center"> Sangeet Bargotra </p>
logo: /assets/img/IMG_8192.jpg

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1lOspB0mBBWOILrmvAQqbGTjB9vfaNpW3/view?usp=sharing">Download</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-sanngeet">LinkedIn</a> |
  <a href="https://github.com/sanngeet">GitHub</a>
  
  <br>   
  Lead Full Stack developer,
  <br>
  Lmeter Global Real Estate
  <br>
  India | Kuwait
  </p>



theme: jekyll-theme-minimal
