title: <p align="center"> Sangeet Bargotra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-sanngeet">LinkedIn</a> |
  <a href="https://github.com/sanngeet">GitHub</a>
  
  <br>   
  I'm working as a lead Full Stack developer for Lmeter Global Real Estate, Kuwait
  <br>
  </p>



theme: jekyll-theme-minimal
