title: <p align="center"> Sangeet Bargotra </p>
logo: /assets/img/IMG_8192.jpg

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1PUkA9zC30Z_DCgGupfChXZZGshjjzQI1/edit?usp=sharing&ouid=108689011955159598657&rtpof=true&sd=true">Download</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-sanngeet">LinkedIn</a> |
  <a href="https://github.com/sanngeet">GitHub</a>
  
  <br>   
  Full Stack developer with an experience of 5 years,
  <br>
  Lmeter Global Real Estate,
  <br>
  India | Kuwait
  </p>



theme: jekyll-theme-minimal
