title: <p align="center"> Sangeet Bargotra </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1PUkA9zC30Z_DCgGupfChXZZGshjjzQI1/edit?usp=sharing&ouid=108689011955159598657&rtpof=true&sd=true">Download</a> |
  <a href="https://www.linkedin.com/in/sanngeet">LinkedIn</a> |
  <a href="https://github.com/sanngeet">GitHub</a>
  <br>   
  Full Stack developer, Kuwait
  </p>



theme: jekyll-theme-minimal
